BEGIN TRY
SELECT 'ITFunda'/0
END TRY
BEGIN CATCH
SELECT ERROR_MESSAGE()[ERROR_MESSAGE], ERROR_NUMBER()[ERROR_NUMBER], ERROR_PROCEDURE()[ERROR_PROCEDURE],
ERROR_SEVERITY() [ERROR_SEVERITY] , ERROR_STATE()[ERROR_STATE], ERROR_LINE()[ERROR_LINE];
-- THROW 50001, 'Always use integer to divide by', 1 (to throw error, uncomment it)
END CATCH

-- WITH RANKS AS
--(
--    SELECT Salary,
--           DENSE_RANK() OVER (ORDER BY Salary DESC) AS DENSERANK
--    FROM [dbo].[Employees]
--)
--SELECT TOP 1 Salary
--FROM RANKS
--WHERE DENSERANK = 2

BEGIN TRY
SELECT 'ITFunda'/0
END TRY
BEGIN CATCH
THROW 50001, 'Always use integer to divide by', 1
END CATCH